version: '3.1'

services:
  skincare.app:
    image: backend-skincare:latest
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: node --inspect index.js
    environment:
      - PORT=8080
    depends_on:
      - skincare.pg
  skincare.pg:
    image: postgres:latest
    volumes:
    - /shared_folder/postgresql:/var/lib/postgresql
    - ./db/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=skincare.pg
      - POSTGRES_USER=skincare
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=skincare
      - POSTGRES_PORT=5432