create user root with encrypted password '1234';
grant all privileges on database skincare to skincare;
grant all privileges on database skincare to root;

\connect skincare

CREATE TABLE ingredient (
    ingr_id INTEGER PRIMARY KEY, 
    friendly_name VARCHAR,
    ingr_name VARCHAR, 
    ingr_desc VARCHAR
);

CREATE TABLE effect (
    effect_id   INTEGER PRIMARY KEY,
    effect_name VARCHAR,
    effect_desc VARCHAR
);

CREATE TABLE ingredient_ingredient (
    ingr_id1 INTEGER REFERENCES ingredient(ingr_id) ON UPDATE CASCADE,
    ingr_id2 INTEGER REFERENCES ingredient(ingr_id) ON UPDATE CASCADE,
    recommendation BOOLEAN, 
    rel_desc VARCHAR,
    PRIMARY KEY (ingr_id1, ingr_id2),
    CHECK (ingr_id1 < ingr_id2)
);

CREATE TABLE skin_type 
(
    skin_id	INTEGER PRIMARY KEY,
    type_name	VARCHAR,
    skin_desc	VARCHAR
);

grant all privileges on table ingredient to skincare;
grant all privileges on table effect to skincare;
grant all privileges on table ingredient_ingredient to skincare;
grant all privileges on table skin_type to skincare;

INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('1', 'Vitamin A', 'Retinol', 'Retinol, also called vitamin A1, is a fat-soluble vitamin in the vitamin A family[1] found in food and used as a dietary supplement.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('2', 'AHA', 'Alpha Hydroxy Acid', 'Alpha-hydroxy acids (AHAs) are a group of plant and animal-derived acids used in a variety of skincare products');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('3', 'BHA', 'Beta Hyodroxy Acid', 'BHAs, on the other hand, are primarily used for acne and sun damage. These products go deep into your hair follicles to dry out excess oils and dead skin cells to unclog your pores. Because of these effects, BHAs are most suitable for combination to oily skin. Lower concentrations may be used to help calm sensitive skin. You may also have more success with BHAs if you wanted to reduce rosacea-related redness.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('4', 'PHA', 'Polyhydroxyalkanoates', 'PHAs are a type of hydroxy (or fruit) acid. Other hydroxy acids include alpha hydroxy acids (AHAs) and beta hydroxy acids (BHAs). All three are added to skin care products to help reverse sun damage, reduce the appearance of wrinkles, and make skin more elastic, toned, and hydrated.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('5', 'Vitamin C', 'Absorbic Acid', 'Vitamin C is a powerful antioxidant that works to stimulate collagen production in your skin. It also fights fine lines, brightens your complexion, and provides a host of other benefits. Skincare experts also tout it as one of the best anti-aging ingredients you could ever use.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('6', 'Benzagel', 'Benzoyl peroxide', 'Benzagel (benzoyl peroxide gel) is a topical (for the skin) antibacterial agent that also has a mild drying effect used to treat acne.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('7', 'Niacinamide', 'Niacinamide', 'Niacinamide helps build cells in the skin while also protecting them from environmental stresses, such as sunlight, pollution, and toxins. Treats acne. Niacinamide may be helpful for severe acne, especially inflammatory forms like papules and pustules. Over time, you may see fewer lesions and improved skin texture.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('8', 'Glycolic Acid', 'Glycolic Acid', 'Glycolic acid is a type of alpha-hydroxy acid (or AHA) that is derived from sugar cane.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('9', 'Salicylic Acid', 'Salicylic Acid', 'Salicylic Acid is a beta hydroxy acid that occurs as a natural compound in plants. It has direct activity as an anti-inflammatory agent and acts as a topical antibacterial agent due to its ability to promote exfoliation.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('10', 'Hyaluronic Acid', 'Hyaluronic Acid', 'Hyaluronic acid supplements can help increase skin moisture and reduce the appearance of fine lines and wrinkles. Topical treatments can soothe redness and dermatitis, while injections can make skin appear firmer.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('11', 'RA', 'Retinoic Acid', 'Retinol stimulates fibroblasts to synthesize collagen fibres (stimulates the activity of fibroblasts and increases their number), improves skin elasticity (removes degenerated elastin fibers) and promotes angiogenesis [13]');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('12', 'Ensulizole', 'Ensulizole', 'Also known as phenylbenzimidazole sulfonic acid, ensulizole is a water soluble sunscreen ingredient that works in the UVB range, offering no UVA protection.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('13', 'Octocrylene', 'Octocrylene', 'Octocrylene is a globally approved sunscreen agent that primarily protects skin from the UVB range of sunlight while providing a small amount of UVA protection. It also helps stabilize the UVA sunscreen ingredient avobenzone. Therefore, the two are often found in the same sunscreen formulas.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('14', 'Avobenzone', 'Avobenzone', 'Avobenzone is an oil-soluble ingredient used in sunscreen products to absorb the full spectrum of UVA rays');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('15', 'Homosalate', 'Homosalate', 'Salicylates prevent direct skin exposure to the suns harmful rays by absorbing ultraviolet (UV) light. Homosalate specifically absorbs short-wave UVB rays, which are associated with DNA damage and increased risk of skin cancer.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('16', 'Oxybenzone', 'Oxybenzone', 'While the primary function of oxybenzone is to absorb UV light, research has shown that it is also absorbed by the skin and stays in our bodies for an unknown amount of time. Oxybenzone is also used in nail polish, fragrances, hair spray, and cosmetics as a photostabilizer.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('17', 'Ferulic Acid', 'Ferulic Acid', 'Ferulic acid is an antioxidant that works to boost the effects of other antioxidants. When used in skin care products, it helps to protect overall skin integrity by reducing the development of fine lines, spots, and wrinkles.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('18', 'Vitamin E', 'Vitamin E', 'Vitamin E is a fat-soluble vitamin that acts as an antioxidant, helping protect cells from damage throughout your body. It s found in our sebum (skin oil), which creates a natural barrier to keep moisture in your skin.');
INSERT INTO ingredient (ingr_id,friendly_name,ingr_name,ingr_desc) VALUES ('19', 'Hydroquinone', 'Hydroquinone', '"Hydroquinone is used to lighten the dark patches of skin also called hyperpigmentation, melasma liver spots age spots freckles) caused by pregnancy, birth control pills, hormone medicine, or injury to the skin. This medicine works by blocking the process in the skin that leads to discoloration."');

INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('1', 'Exfoliant', 'Exfoliation is a crucial part of any skin care routine, but it can also be intimidating for those who are just starting their beauty regimen and are unsure of what exactly an exfoliator does. To put it simply, any product or device used on the skin to remove dead skin cells is an exfoliator, which can then be classified as either chemical or physical.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('2', 'Hydrating', 'Your body needs water to function, period. That includes your skin, which needs a healthy amount of that water in your skin cells for them to function properly and for your skin to look its best. Although the main way to increase water content in your skin is to drink plenty of water and eat fruits and vegetables with high water content, there are other ways to boost skin hydration, too. Thats where hydrating skincare products step onto the scene! Hydrating products can be anything, from facial cleansers, to creams, to serums. Applying a hydrator to your skin allows your skin cells to absorb moisture and water, making them swell. Humectants are ideal hydrators in skincare. Humectants are products or ingredients that are structurally designed to attract water molecules from your surroundings. ');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('3', 'Mosturizer', 'To help keep your skin looking younger, Lolis recommends using moisturizer from head to toe. The face, neck and décolletage should get moisturizer twice daily as should elbows, knees and feet, she says. There are many kinds of moisturizers available for different skin types, but if you really want to keep your skin hydrated, look for moisturizers that contain glycerin or hyaluronic acid, suggests Jaliman.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('4', 'Cleanser', 'Most dermatologists agree it is important to cleanse the face twice daily to get bacteria, dirt and pollutants off your skin. However, there are different types of cleansers that are more ideal for certain types of skin.  The common mistakes people make are using the same product in the morning and at night and not getting a product that is ideal for their skin type, says Dr. Lolis. For example, someone prone to breakouts may use a cleanser with salicylic acid only to find it has a reverse effect. When skin is dried out, it increases oil production, which can only make a breakout more prevalent. The best approach would be to see a dermatologist for a skin assessment and a product recommendation that is most suitable for your skin type.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('5', 'Treatment', 'Treatment products are used to address specific skin concerns such as acne, dark spots, hyperpigmentation, fine lines and inflammation. Skin treatment products are all regulated and have to be approved by the FDA. They can be in the forms of creams, gels, lotions, solutions, serums and medicated facial pads, explains Dr. Tonkovic-Capin.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('6', 'Serum', 'Serums usually contain antioxidants, which help fight free radical damage, says Dr. Jaliman. They can also contain anti-aging ingredients such as retinols and peptides, which stimulate collagen production. Because they penetrate deep into the skin, these products are great for hydrating dry skin. They are best used after your cleanser, and they can be used underneath moisturizer to treat the skin while sleeping.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('7', 'Oil', 'Nutrient-filled face oils help to build a resilient layer for your skin, no matter your skin type. They can be very hydrating, which makes them especially useful for those with dry skin. Argan oil and vitamin E are great for pretty much every skin type and issue, says Lolis. Ideally, add two or three drops to a moisturizer or serum. For acne-prone skin, tea tree oil will work very well and vitamin C oil will help with any scarring.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('8', 'Sunscreen', 'Sunscreens are essential for protecting your skin from UV damage, no matter the season. Luckily, there are plenty of ways to apply sunscreen beyond just the typical bottle. Everyone should be using a moisturizer with SPF even in winter, says Lolis. If you’re outside or live in warmer climates, its even more important to protect your face. The key is to know your skin type and use sunscreen that is a suitable fit. Some sunscreens are greasy and may clog pores. This is why its best to use a moisturizer formulated to address a particular skin issue that has sunscreen built in.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('9', 'Peeling', 'Peeling remove the outer layer of the skin, which means they tend to go deeper to remove more excess dead skin cells than exfoliators. They usually contain glycolic, salicylic or lactic acids. Use it once every two weeks, but avoid these if you are prone to rosacea and eczema, says Jaliman. Chemical peels tend to be more intense and typically are done by a professional, but there are also at-home DIY peels available to address things such as acne scars, wrinkles, sun damage and hyperpigmentation.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('10', 'Toner', 'Toner can be used after a cleanser twice a day to remove excess traces of makeup or other residue from the skin. Toners shrink pores and restore skin to its natural pH balance, says Lolis. This is important because when our pH levels are thrown out of whack due to soaps and chemicals in cleansers, oil production increases, causing a cycle of breakouts. Those with sensitive skin should use an alcohol-free toner.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('11', 'Masks', 'There are many different types of masks on the market, ranging from hydrating to drying and even brightening, which makes them useful for all skin types. Done weekly, youll see a change to skin, and breakouts will have a chance to dry up and heal, says Lolis. I am also a fan of using soothing masks on the cheeks and then a clarifying mask on the forehead, chin and jawline. Its okay to mix it up. The key is to apply a mask to clean, exfoliated skin so there isnt anything blocking it from penetrating the skin.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('12', 'Eye-cream', 'Eye creams tend to be formulated for specific eye area issues such as puffiness, wrinkles and dark circles. There are some creams that tackle several issues at once, and these contain things like caffeine, glycerine, chamomile, hyaluronic acid, antioxidants and peptides, says Lolis. Eye creams are specially formulated to penetrate the finer skin around the eyes. They can be used once or twice a day, but look for retinol or peptide eye creams to use at night, as they stimulate collagen production, suggests Jaliman.');
INSERT INTO effect (effect_id,effect_name,effect_desc) VALUES ('13', 'Acne', 'Treatments work to clear away bacteria and dry up the excess oils that lead to acne.');

INSERT INTO skin_type (skin_id,type_name,skin_desc) VALUES ('1', 'Normal', 'This is skin that has fine pores, healthy blood circulation, and a smooth texture. It can become dryer with aging in a condition that doctors may refer to as age-induced dryness.');
INSERT INTO skin_type (skin_id,type_name,skin_desc) VALUES ('2', 'Dry', 'This skin produces less sebum than normal skin. This means that it is unable to lock in moisture and protect itself from external germs. People with dry skin may experience scaling, flakiness in patches, itchiness, and feelings of tightness.');
INSERT INTO skin_type (skin_id,type_name,skin_desc) VALUES ('3', 'Oily', 'This type of skin overproduces sebum, sometimes due to hormonal changes, stress, and medication use. The skin usually has visible pores and a glossy shine, and it may be prone to acne.');
INSERT INTO skin_type (skin_id,type_name,skin_desc) VALUES ('4', 'Combination skin', 'This skin has some areas that are oily and some that are dry. For example, people with combination skin may have an oily forehead, chin, and nose but normal-to-dry cheeks.');
INSERT INTO skin_type (skin_id,type_name,skin_desc) VALUES ('5', 'Sensitive', 'People with sensitive skin are more prone to inflammation or adverse reactions. Sensitive skin can be a symptom of conditions such as rosacea or eczema.');
INSERT INTO skin_type (skin_id,type_name,skin_desc) VALUES ('6', 'Rosacea', 'A condition that causes redness and often small, red, pus-filled bumps on the face. Rosacea most commonly affects middle-aged women with fair skin. It can be mistaken for acne or other skin conditions. Key symptoms are facial redness with swollen red bumps and small visible blood vessels. Treatments such as antibiotics or anti-acne medication can control and reduce symptoms. Left untreated, it tends to worsen over time.');
INSERT INTO skin_type (skin_id,type_name,skin_desc) VALUES ('7', 'Psoriasis', 'A condition in which skin cells build up and form scales and itchy, dry patches. Psoriasis is thought to be an immune system problem. Triggers include infections, stress and cold. The most common symptom is a rash on the skin, but sometimes the rash involves the nails or joints. Treatment aims to remove scales and stop skin cells from growing so quickly. Topical ointments, light therapy and medication can offer relief.');


INSERT INTO ingredient_ingredient(ingr_id1, ingr_id2, recommendation, rel_desc) VALUES (1, 2, false, 'Experts generally advise not using the two ingredients at the exact same time, since this can lead to dryness and irritation.');